version: 2

project_name: kmctl

before:
  hooks:
    - go mod tidy

builds:
  - id: kmctl
    main: .
    binary: kmctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/kubemoot/kmctl/internal/version.Version={{ .Version }}
      - -X github.com/kubemoot/kmctl/internal/version.Commit={{ .ShortCommit }}
      - -X github.com/kubemoot/kmctl/internal/version.Date={{ .Date }}

archives:
  - id: kmctl
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: kubemoot
    name: kmctl
  draft: false
  prerelease: auto
