sonar.projectKey=kmctl
sonar.projectName=kmctl
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,bin/**,dist/**
sonar.go.coverage.reportPaths=cover.out
sonar.sourceEncoding=UTF-8
